import { SearchItem } from "@/lib/types";

export const fallbackFeaturedTitles: SearchItem[] = [
  {
    id: "tv-95479-season-3",
    sourceId: 95479,
    href: "/title/tv/95479?season=3",
    title: "The White Lotus Season 3",
    seriesTitle: "The White Lotus",
    seasonNumber: 3,
    seasonLabel: "Season 3",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-02-16",
    votes: 245000,
    overview: "A luxury holiday turns quietly chaotic.",
    availableSeasons: []
  },
  {
    id: "tv-100088-season-2",
    sourceId: 100088,
    href: "/title/tv/100088?season=2",
    title: "The Last of Us Season 2",
    seriesTitle: "The Last of Us",
    seasonNumber: 2,
    seasonLabel: "Season 2",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-04-13",
    votes: 590000,
    overview: "Still culturally dangerous territory.",
    availableSeasons: []
  },
  {
    id: "tv-94997-season-2",
    sourceId: 94997,
    href: "/title/tv/94997?season=2",
    title: "House of the Dragon Season 2",
    seriesTitle: "House of the Dragon",
    seasonNumber: 2,
    seasonLabel: "Season 2",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-03-03",
    votes: 520000,
    overview: "Dragons, politics, and things you should maybe not ruin.",
    availableSeasons: []
  },
  {
    id: "tv-95396-season-2",
    sourceId: 95396,
    href: "/title/tv/95396?season=2",
    title: "Severance Season 2",
    seriesTitle: "Severance",
    seasonNumber: 2,
    seasonLabel: "Season 2",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-01-17",
    votes: 410000,
    overview: "A show people absolutely will get mad about.",
    availableSeasons: []
  },
  {
    id: "tv-1438-season-3",
    sourceId: 1438,
    href: "/title/tv/1438?season=3",
    title: "The Gilded Age Season 3",
    seriesTitle: "The Gilded Age",
    seasonNumber: 3,
    seasonLabel: "Season 3",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-03-10",
    votes: 36000,
    overview: "Corsets, tension, and potential spoiler crimes.",
    availableSeasons: []
  },
  {
    id: "tv-110316-season-3",
    sourceId: 110316,
    href: "/title/tv/110316?season=3",
    title: "Euphoria Season 3",
    seriesTitle: "Euphoria",
    seasonNumber: 3,
    seasonLabel: "Season 3",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-03-01",
    votes: 125000,
    overview: "Still the sort of title where you should ask first.",
    availableSeasons: []
  },
  {
    id: "tv-46648-season-5",
    sourceId: 46648,
    href: "/title/tv/46648?season=5",
    title: "True Detective Season 5",
    seriesTitle: "True Detective",
    seasonNumber: 5,
    seasonLabel: "Season 5",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-02-09",
    votes: 710000,
    overview: "Huge enough to talk about soon, not necessarily yet.",
    availableSeasons: []
  },
  {
    id: "tv-194764-season-1",
    sourceId: 194764,
    href: "/title/tv/194764?season=1",
    title: "The Penguin Season 1",
    seriesTitle: "The Penguin",
    seasonNumber: 1,
    seasonLabel: "Season 1",
    year: "2025",
    mediaType: "tv",
    type: "series",
    releaseDate: "2025-03-24",
    votes: 92000,
    overview: "Still in the zone where decent people stay vague.",
    availableSeasons: []
  }
];
